# Generated by Django 4.1.3 on 2023-01-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=10.55),
        ),
    ]
