# Generated by Django 4.1.3 on 2023-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bannerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_perfume', models.CharField(max_length=100)),
            ],
        ),
    ]
