# Generated by Django 4.1.3 on 2023-01-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_perfume_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_product',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
