# Generated by Django 4.1.3 on 2023-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=10.55)),
                ('image', models.ImageField(upload_to='')),
                ('description_product', models.TextField(max_length=1000)),
            ],
        ),
    ]
