# Generated by Django 4.1.3 on 2023-02-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cartitems_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='combo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.combo'),
            preserve_default=False,
        ),
    ]
