# Generated by Django 4.1.3 on 2023-02-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_cartitems_combo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
