# Generated by Django 4.1.3 on 2023-02-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
