# Generated by Django 4.1.3 on 2023-02-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combo',
            field=models.BooleanField(default=False),
        ),
    ]
