# Generated by Django 4.1.3 on 2023-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_ingredients_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
