# Generated by Django 4.1.3 on 2023-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_bannerproduct_product_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_include',
            field=models.BooleanField(default=False),
        ),
    ]
