# Generated by Django 4.1.3 on 2023-02-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
